/*==============================================================================
  VW_DIM_DATE_WITH_DYNAMIC_FLAGS - BUSINESS CALENDAR SYSTEM

  This view exposes the DIM_DATE static calendar dimension along with dynamic,
  time-relative flags and offsets calculated at query time. It also integrates
  Australian public holiday data sourced from data.gov.au.

  USAGE:
  ------
  Query this view to access all static calendar attributes, dynamic flags,
  relative offsets, and holiday indicators.

  STRUCTURE:
  ----------
  - Includes all columns from DIM_DATE
  - Adds dynamic Boolean flags (e.g., IS_TODAY, IS_THIS_MONTH)
  - Adds relative offset columns (e.g., RELATIVE_DAY_OFFSET)
  - Adds optional descriptive columns (e.g., RELATIVE_MONTH_DESCRIPTION)
  - Adds holiday columns (IS_PUBLIC_HOLIDAY, HOLIDAY_NAME, HOLIDAY_JURISDICTION)

  NOTES:
  ------
  - Dynamic calculations use CURRENT_DATE() for accuracy at query time
  - Holidays sourced from PUBLIC_HOLIDAYS_AU table
  - Designed for BI consumption and simplified filtering

  AUTHOR: Snowflake Assistant
  DATE CREATED: 2025-04-06
  LAST MODIFIED: 2025-04-06
==============================================================================*/

CREATE OR REPLACE VIEW VW_DIM_DATE_WITH_DYNAMIC_FLAGS AS
SELECT
    d.*,

    -- Holiday Flags
    CASE WHEN h.HOLIDAY_DATE IS NOT NULL THEN TRUE ELSE FALSE END AS IS_PUBLIC_HOLIDAY,
    h.HOLIDAY_NAME,
    h.JURISDICTION AS HOLIDAY_JURISDICTION,

    -- Dynamic Flags
    DATE_KEY = CURRENT_DATE() AS IS_TODAY,
    DATE_KEY = DATEADD(DAY, -1, CURRENT_DATE()) AS IS_YESTERDAY,
    DATE_KEY = DATEADD(DAY, 1, CURRENT_DATE()) AS IS_TOMORROW,

    DATE_TRUNC('WEEK', DATE_KEY) = DATE_TRUNC('WEEK', CURRENT_DATE()) AS IS_THIS_WEEK,
    DATE_TRUNC('WEEK', DATE_KEY) = DATEADD(WEEK, -1, DATE_TRUNC('WEEK', CURRENT_DATE())) AS IS_LAST_WEEK,
    DATE_TRUNC('WEEK', DATE_KEY) = DATEADD(WEEK, 1, DATE_TRUNC('WEEK', CURRENT_DATE())) AS IS_NEXT_WEEK,

    DATE_TRUNC('MONTH', DATE_KEY) = DATE_TRUNC('MONTH', CURRENT_DATE()) AS IS_THIS_MONTH,
    DATE_TRUNC('MONTH', DATE_KEY) = DATEADD(MONTH, -1, DATE_TRUNC('MONTH', CURRENT_DATE())) AS IS_LAST_MONTH,
    DATE_TRUNC('MONTH', DATE_KEY) = DATEADD(MONTH, 1, DATE_TRUNC('MONTH', CURRENT_DATE())) AS IS_NEXT_MONTH,

    DATE_TRUNC('QUARTER', DATE_KEY) = DATE_TRUNC('QUARTER', CURRENT_DATE()) AS IS_THIS_QUARTER,
    DATE_TRUNC('QUARTER', DATE_KEY) = DATEADD(QUARTER, -1, DATE_TRUNC('QUARTER', CURRENT_DATE())) AS IS_LAST_QUARTER,
    DATE_TRUNC('QUARTER', DATE_KEY) = DATEADD(QUARTER, 1, DATE_TRUNC('QUARTER', CURRENT_DATE())) AS IS_NEXT_QUARTER,

    DATE_TRUNC('YEAR', DATE_KEY) = DATE_TRUNC('YEAR', CURRENT_DATE()) AS IS_THIS_YEAR,
    DATE_TRUNC('YEAR', DATE_KEY) = DATEADD(YEAR, -1, DATE_TRUNC('YEAR', CURRENT_DATE())) AS IS_LAST_YEAR,
    DATE_TRUNC('YEAR', DATE_KEY) = DATEADD(YEAR, 1, DATE_TRUNC('YEAR', CURRENT_DATE())) AS IS_NEXT_YEAR,

    -- Period to date flags
    (DATE_KEY BETWEEN DATE_TRUNC('YEAR', CURRENT_DATE()) AND CURRENT_DATE()) AS IS_YTD,
    (DATE_KEY BETWEEN DATE_TRUNC('QUARTER', CURRENT_DATE()) AND CURRENT_DATE()) AS IS_QTD,
    (DATE_KEY BETWEEN DATE_TRUNC('MONTH', CURRENT_DATE()) AND CURRENT_DATE()) AS IS_MTD,
    (DATE_KEY BETWEEN DATE_TRUNC('WEEK', CURRENT_DATE()) AND CURRENT_DATE()) AS IS_WTD,

    -- Rolling window flags
    (DATE_KEY BETWEEN DATEADD(DAY, -6, CURRENT_DATE()) AND CURRENT_DATE()) AS IS_LAST_7_DAYS,
    (DATE_KEY BETWEEN DATEADD(DAY, -29, CURRENT_DATE()) AND CURRENT_DATE()) AS IS_LAST_30_DAYS,
    (DATE_KEY BETWEEN DATEADD(DAY, -89, CURRENT_DATE()) AND CURRENT_DATE()) AS IS_LAST_90_DAYS,
    (DATE_KEY BETWEEN DATEADD(DAY, -364, CURRENT_DATE()) AND CURRENT_DATE()) AS IS_LAST_365_DAYS,

    -- Relative Offsets
    DATEDIFF(DAY, CURRENT_DATE(), DATE_KEY) AS RELATIVE_DAY_OFFSET,
    DATEDIFF(WEEK, CURRENT_DATE(), DATE_KEY) AS RELATIVE_WEEK_OFFSET,
    DATEDIFF(MONTH, CURRENT_DATE(), DATE_KEY) AS RELATIVE_MONTH_OFFSET,
    DATEDIFF(QUARTER, CURRENT_DATE(), DATE_KEY) AS RELATIVE_QUARTER_OFFSET,
    DATEDIFF(YEAR, CURRENT_DATE(), DATE_KEY) AS RELATIVE_YEAR_OFFSET,

    -- Optional descriptive offset
    CASE 
        WHEN DATEDIFF(MONTH, CURRENT_DATE(), DATE_KEY) = 0 THEN 'This Month'
        WHEN DATEDIFF(MONTH, CURRENT_DATE(), DATE_KEY) = -1 THEN 'Last Month'
        WHEN DATEDIFF(MONTH, CURRENT_DATE(), DATE_KEY) = 1 THEN 'Next Month'
        WHEN DATEDIFF(MONTH, CURRENT_DATE(), DATE_KEY) < -1 THEN CONCAT(ABS(DATEDIFF(MONTH, CURRENT_DATE(), DATE_KEY)), ' Months Ago')
        WHEN DATEDIFF(MONTH, CURRENT_DATE(), DATE_KEY) > 1 THEN CONCAT('In ', DATEDIFF(MONTH, CURRENT_DATE(), DATE_KEY), ' Months')
        ELSE NULL
    END AS RELATIVE_MONTH_DESCRIPTION

FROM DIM_DATE d
LEFT JOIN PUBLIC_HOLIDAYS_AU h
    ON d.DATE_KEY = h.HOLIDAY_DATE;