/*==============================================================================
  VW_DIM_DATE_WITH_DYNAMIC_FLAGS - BUSINESS CALENDAR SYSTEM

  This view exposes the unified calendar dimension (`DIM_DATE_UNIFIED`) along with
  dynamic, time-relative flags and offsets calculated at query time.

  USAGE:
  ------
  Run this script to create or replace the dynamic calendar view.

  Usage Example:
  --------------
  ```sql
  SELECT * FROM VW_DIM_DATE_WITH_DYNAMIC_FLAGS WHERE IS_YTD = TRUE;
  ```

  STRUCTURE:
  ----------
  - Includes all columns from `DIM_DATE_UNIFIED`
  - Adds dynamic Boolean flags (e.g., IS_TODAY, IS_THIS_MONTH)
  - Adds relative offset columns (e.g., RELATIVE_DAY_OFFSET)
  - Adds optional descriptive columns (e.g., RELATIVE_MONTH_DESCRIPTION)

  NOTES:
  ------
  - Dynamic calculations use CURRENT_DATE() for accuracy at query time
  - Designed for BI consumption and simplified filtering
  - No data is stored; all flags are computed on demand

  AUTHOR: Andrew Exley, Lument Pty Ltd
  DATE CREATED: 2025-04-06
  LAST MODIFIED: 2025-04-06
==============================================================================*/

CREATE OR REPLACE VIEW VW_DIM_DATE_WITH_DYNAMIC_FLAGS AS
SELECT
    d.*,

    -- Dynamic Flags
    d.DATE_KEY = CURRENT_DATE() AS IS_TODAY,
    d.DATE_KEY = DATEADD(DAY, -1, CURRENT_DATE()) AS IS_YESTERDAY,
    d.DATE_KEY = DATEADD(DAY, 1, CURRENT_DATE()) AS IS_TOMORROW,

    DATE_TRUNC('WEEK', d.DATE_KEY) = DATE_TRUNC('WEEK', CURRENT_DATE()) AS IS_THIS_WEEK,
    DATE_TRUNC('WEEK', d.DATE_KEY) = DATEADD(WEEK, -1, DATE_TRUNC('WEEK', CURRENT_DATE())) AS IS_LAST_WEEK,
    DATE_TRUNC('WEEK', d.DATE_KEY) = DATEADD(WEEK, 1, DATE_TRUNC('WEEK', CURRENT_DATE())) AS IS_NEXT_WEEK,

    DATE_TRUNC('MONTH', d.DATE_KEY) = DATE_TRUNC('MONTH', CURRENT_DATE()) AS IS_THIS_MONTH,
    DATE_TRUNC('MONTH', d.DATE_KEY) = DATEADD(MONTH, -1, DATE_TRUNC('MONTH', CURRENT_DATE())) AS IS_LAST_MONTH,
    DATE_TRUNC('MONTH', d.DATE_KEY) = DATEADD(MONTH, 1, DATE_TRUNC('MONTH', CURRENT_DATE())) AS IS_NEXT_MONTH,

    DATE_TRUNC('QUARTER', d.DATE_KEY) = DATE_TRUNC('QUARTER', CURRENT_DATE()) AS IS_THIS_QUARTER,
    DATE_TRUNC('QUARTER', d.DATE_KEY) = DATEADD(QUARTER, -1, DATE_TRUNC('QUARTER', CURRENT_DATE())) AS IS_LAST_QUARTER,
    DATE_TRUNC('QUARTER', d.DATE_KEY) = DATEADD(QUARTER, 1, DATE_TRUNC('QUARTER', CURRENT_DATE())) AS IS_NEXT_QUARTER,

    DATE_TRUNC('YEAR', d.DATE_KEY) = DATE_TRUNC('YEAR', CURRENT_DATE()) AS IS_THIS_YEAR,
    DATE_TRUNC('YEAR', d.DATE_KEY) = DATEADD(YEAR, -1, DATE_TRUNC('YEAR', CURRENT_DATE())) AS IS_LAST_YEAR,
    DATE_TRUNC('YEAR', d.DATE_KEY) = DATEADD(YEAR, 1, DATE_TRUNC('YEAR', CURRENT_DATE())) AS IS_NEXT_YEAR,

    -- Period to date flags
    (d.DATE_KEY BETWEEN DATE_TRUNC('YEAR', CURRENT_DATE()) AND CURRENT_DATE()) AS IS_YTD,
    (d.DATE_KEY BETWEEN DATE_TRUNC('QUARTER', CURRENT_DATE()) AND CURRENT_DATE()) AS IS_QTD,
    (d.DATE_KEY BETWEEN DATE_TRUNC('MONTH', CURRENT_DATE()) AND CURRENT_DATE()) AS IS_MTD,
    (d.DATE_KEY BETWEEN DATE_TRUNC('WEEK', CURRENT_DATE()) AND CURRENT_DATE()) AS IS_WTD,

    -- Rolling window flags
    (d.DATE_KEY BETWEEN DATEADD(DAY, -6, CURRENT_DATE()) AND CURRENT_DATE()) AS IS_LAST_7_DAYS,
    (d.DATE_KEY BETWEEN DATEADD(DAY, -29, CURRENT_DATE()) AND CURRENT_DATE()) AS IS_LAST_30_DAYS,
    (d.DATE_KEY BETWEEN DATEADD(DAY, -89, CURRENT_DATE()) AND CURRENT_DATE()) AS IS_LAST_90_DAYS,
    (d.DATE_KEY BETWEEN DATEADD(DAY, -364, CURRENT_DATE()) AND CURRENT_DATE()) AS IS_LAST_365_DAYS,

    -- Relative Offsets
    DATEDIFF(DAY, CURRENT_DATE(), d.DATE_KEY) AS RELATIVE_DAY_OFFSET,
    DATEDIFF(WEEK, CURRENT_DATE(), d.DATE_KEY) AS RELATIVE_WEEK_OFFSET,
    DATEDIFF(MONTH, CURRENT_DATE(), d.DATE_KEY) AS RELATIVE_MONTH_OFFSET,
    DATEDIFF(QUARTER, CURRENT_DATE(), d.DATE_KEY) AS RELATIVE_QUARTER_OFFSET,
    DATEDIFF(YEAR, CURRENT_DATE(), d.DATE_KEY) AS RELATIVE_YEAR_OFFSET,

    -- Optional descriptive offset
    CASE 
        WHEN DATEDIFF(MONTH, CURRENT_DATE(), d.DATE_KEY) = 0 THEN 'This Month'
        WHEN DATEDIFF(MONTH, CURRENT_DATE(), d.DATE_KEY) = -1 THEN 'Last Month'
        WHEN DATEDIFF(MONTH, CURRENT_DATE(), d.DATE_KEY) = 1 THEN 'Next Month'
        WHEN DATEDIFF(MONTH, CURRENT_DATE(), d.DATE_KEY) < -1 THEN CONCAT(ABS(DATEDIFF(MONTH, CURRENT_DATE(), d.DATE_KEY)), ' Months Ago')
        WHEN DATEDIFF(MONTH, CURRENT_DATE(), d.DATE_KEY) > 1 THEN CONCAT('In ', DATEDIFF(MONTH, CURRENT_DATE(), d.DATE_KEY), ' Months')
        ELSE NULL
    END AS RELATIVE_MONTH_DESCRIPTION

FROM DIM_DATE_UNIFIED d;